### PR TITLE
Bump version to 0.1.1, Update Changelog

### PR DESCRIPTION
**Pull request by chlafreniere**
Bump version to 0.1.1, Update Changelog with quick description of bug fix.

### CODE REVIEW

**Comment by vors** [comment]
This is a git nit: the commit history should not look like this (it includes old commits)
image


That's not a biggy since you can simply use the "Squash and merge" button to do the right thing, but I suggest to learn how to avoid such things in the future and have a nice intentional commits in PRs.

**Review by vors — APPROVED** [review]
LGTM, not merging because you can do it yourself! :)

**Comment by chlafreniere** [comment]
Thanks, @vors!

Looks like I can't merge myself actually:

image

**Comment by vors** [comment]
You need to accept the invitation to be the maintainer 

image


Here is a link to accept: https://github.com/vors/jupyter-powershell/invitations

**Pull request merged**
